### ISSUE TITLE
[TODO] 특징 추출 과정 (Feature Extraction)  & 모델 파라미터 최적화 (Model Parameter Optimization) 

### ISSUE THREAD

**Issue by kimkwangho82** [kimkwangho82/ClovaCall#1]
## 1. 특징 추출 과정 (Feature Extraction)
Ref: https://github.com/espnet/espnet/blob/96b2fd08d4fd9276aabd7ad41ec5e02a88b30958/espnet2/asr/frontend/default.py#L63
- [x] (1) Load_wav (normalize=True, [-1, 1])
- [x] (2) STFT (using 'torch.stft')
- [x] (3) Power-Spectrogram
- [x] (4) Log Mel-Fbank (using 'librosa.filters.mel') # 
- [ ] (5) global MVN

## 2. 모델 파라미터 최적화 (Model Parameter Optimization) 
Ref: https://github.com/espnet/espnet/blob/c9b18daa137c9863f97644f3fc10cfdae716bd18/egs2/zeroth_korean/asr1/conf/tuning/train_asr_rnn.yaml

- [ ] (1) Encoder
```
num_layers = 4
hidden_size = 320
```

- [ ] (1) Decoder
```
num_layers = 1
hidden_size = 320
```
